import {
  Document, Paragraph, TextRun, HeadingLevel,
  AlignmentType, Packer, BorderStyle,
  Table, TableRow, TableCell, WidthType,
  type FileChild,
} from 'docx'
import { saveAs } from 'file-saver'

// ── Markdown parser ───────────────────────────────────────────────────────────
function parseInline(text: string): TextRun[] {
  const runs: TextRun[] = []
  // Split by **bold** and *italic* markers
  const parts = text.split(/(\*\*[^*]+\*\*|\*[^*]+\*|`[^`]+`)/)
  for (const part of parts) {
    if (part.startsWith('**') && part.endsWith('**')) {
      runs.push(new TextRun({ text: part.slice(2, -2), bold: true }))
    } else if (part.startsWith('*') && part.endsWith('*')) {
      runs.push(new TextRun({ text: part.slice(1, -1), italics: true }))
    } else if (part.startsWith('`') && part.endsWith('`')) {
      runs.push(new TextRun({ text: part.slice(1, -1), font: 'Courier New' }))
    } else if (part) {
      runs.push(new TextRun(part))
    }
  }
  return runs.length ? runs : [new TextRun(text)]
}

function markdownToParagraphs(markdown: string): Paragraph[] {
  const lines = markdown.split('\n')
  const paragraphs: Paragraph[] = []

  for (const line of lines) {
    if (!line.trim() || line.startsWith('---')) {
      paragraphs.push(new Paragraph({ text: '' }))
      continue
    }
    if (line.startsWith('# ')) {
      paragraphs.push(new Paragraph({ text: line.slice(2), heading: HeadingLevel.HEADING_1 }))
    } else if (line.startsWith('## ')) {
      paragraphs.push(new Paragraph({ text: line.slice(3), heading: HeadingLevel.HEADING_2 }))
    } else if (line.startsWith('### ')) {
      paragraphs.push(new Paragraph({ text: line.slice(4), heading: HeadingLevel.HEADING_3 }))
    } else if (line.startsWith('- ') || line.startsWith('* ')) {
      paragraphs.push(new Paragraph({
        children: parseInline(line.slice(2)),
        bullet: { level: 0 },
      }))
    } else if (line.match(/^\d+\. /)) {
      paragraphs.push(new Paragraph({
        children: parseInline(line.replace(/^\d+\. /, '')),
        numbering: { reference: 'default-numbering', level: 0 },
      }))
    } else {
      paragraphs.push(new Paragraph({ children: parseInline(line) }))
    }
  }
  return paragraphs
}

function metaRow(label: string, value: string) {
  return new TableRow({
    children: [
      new TableCell({
        children: [new Paragraph({ children: [new TextRun({ text: label, bold: true })] })],
        width: { size: 30, type: WidthType.PERCENTAGE },
        borders: {
          top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE },
        },
      }),
      new TableCell({
        children: [new Paragraph(value)],
        width: { size: 70, type: WidthType.PERCENTAGE },
        borders: {
          top: { style: BorderStyle.NONE }, bottom: { style: BorderStyle.SINGLE, size: 1, color: 'E0E0E0' },
          left: { style: BorderStyle.NONE }, right: { style: BorderStyle.NONE },
        },
      }),
    ],
  })
}

// ── TA Report DOCX ────────────────────────────────────────────────────────────
export async function downloadTAReportDocx(params: {
  symbol: string; companyName: string; period: string
  generatedAt: string; reportText: string; modelUsed?: string
}) {
  const date = new Date(params.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })

  const doc = new Document({
    numbering: {
      config: [{
        reference: 'default-numbering',
        levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.LEFT }],
      }],
    },
    sections: [{
      children: [
        new Paragraph({
          children: [new TextRun({ text: `${params.symbol} — Technical Analysis Report`, bold: true, size: 40 })],
          heading: HeadingLevel.TITLE,
        }),
        new Table({
          width: { size: 100, type: WidthType.PERCENTAGE },
          rows: [
            metaRow('Company', params.companyName),
            metaRow('Period', params.period.toUpperCase()),
            metaRow('Date', date),
            ...(params.modelUsed ? [metaRow('Model', params.modelUsed)] : []),
            metaRow('Source', 'Adaptive Market'),
          ],
        }),
        new Paragraph({ text: '' }),
        new Paragraph({
          children: [new TextRun({ text: 'Report', bold: true, size: 28 })],
          heading: HeadingLevel.HEADING_1,
        }),
        ...markdownToParagraphs(params.reportText),
        new Paragraph({ text: '' }),
        new Paragraph({
          children: [new TextRun({ text: 'This report is generated by AI and is not financial advice.', italics: true, color: '888888', size: 18 })],
        }),
      ],
    }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${params.symbol}_TA_Report_${date.replace(/,?\s/g, '_')}.docx`)
}

// ── Valuation Report DOCX ─────────────────────────────────────────────────────
export async function downloadValuationDocx(params: {
  symbol: string; companyName: string; generatedAt: string
  intrinsicValue: number; currentPrice: number; marginOfSafety: number
  reportText: string | null
  dcfBridge?: {
    pvFCFFs: number; pvTerminalValue: number; valueOfOperatingAssets: number
    lessDebt: number; plusCash: number; plusNonOperatingAssets: number
    valueOfEquity: number; wacc: number
  } | null
}) {
  const date = new Date(params.generatedAt).toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  })
  const isUnder = params.marginOfSafety < 0
  const mosAbs = Math.abs(params.marginOfSafety * 100).toFixed(1)
  const mosLabel = isUnder ? `${mosAbs}% Undervalued` : `${mosAbs}% Overvalued`
  const $M = (n: number) => `$${n.toLocaleString('en-US', { maximumFractionDigits: 0 })}M`

  const children: FileChild[] = [
    new Paragraph({
      children: [new TextRun({ text: `${params.symbol} — DCF Valuation Report`, bold: true, size: 40 })],
      heading: HeadingLevel.TITLE,
    }),
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        metaRow('Company', params.companyName),
        metaRow('Date', date),
        metaRow('Intrinsic Value', `$${params.intrinsicValue.toFixed(2)}`),
        metaRow('Price at Analysis', `$${params.currentPrice.toFixed(2)}`),
        metaRow('Assessment', mosLabel),
        ...(params.dcfBridge ? [metaRow('WACC', `${(params.dcfBridge.wacc * 100).toFixed(2)}%`)] : []),
      ],
    }),
    new Paragraph({ text: '' }),
  ]

  if (params.dcfBridge) {
    children.push(
      new Paragraph({ children: [new TextRun({ text: 'Value Bridge', bold: true, size: 28 })], heading: HeadingLevel.HEADING_1 }),
      new Table({
        width: { size: 100, type: WidthType.PERCENTAGE },
        rows: [
          metaRow('PV of FCFFs (Yr 1–10)', $M(params.dcfBridge.pvFCFFs)),
          metaRow('PV of Terminal Value', $M(params.dcfBridge.pvTerminalValue)),
          metaRow('Value of Operating Assets', $M(params.dcfBridge.valueOfOperatingAssets)),
          metaRow('− Debt', $M(params.dcfBridge.lessDebt)),
          metaRow('+ Cash', $M(params.dcfBridge.plusCash)),
          metaRow('Equity Value', $M(params.dcfBridge.valueOfEquity)),
        ],
      }),
      new Paragraph({ text: '' }),
    )
  }

  if (params.reportText) {
    children.push(
      new Paragraph({ children: [new TextRun({ text: 'AI Analysis', bold: true, size: 28 })], heading: HeadingLevel.HEADING_1 }),
      ...markdownToParagraphs(params.reportText),
      new Paragraph({ text: '' }),
    )
  }

  children.push(
    new Paragraph({
      children: [new TextRun({ text: 'This report is generated by AI and is not financial advice.', italics: true, color: '888888', size: 18 })],
    }),
  )

  const doc = new Document({
    numbering: {
      config: [{
        reference: 'default-numbering',
        levels: [{ level: 0, format: 'decimal', text: '%1.', alignment: AlignmentType.LEFT }],
      }],
    },
    sections: [{ children }],
  })

  const blob = await Packer.toBlob(doc)
  saveAs(blob, `${params.symbol}_Valuation_${date.replace(/,?\s/g, '_')}.docx`)
}
