export interface TickerList {
  id: string
  label: string
  description: string
  color: string
  tickers: { symbol: string; name: string }[]
}

export const TICKER_LISTS: TickerList[] = [
  {
    id: 'mag7',
    label: 'Magnificent 7',
    description: 'The 7 mega-cap tech leaders',
    color: '#4DBBFF',
    tickers: [
      { symbol: 'AAPL',  name: 'Apple' },
      { symbol: 'MSFT',  name: 'Microsoft' },
      { symbol: 'NVDA',  name: 'NVIDIA' },
      { symbol: 'AMZN',  name: 'Amazon' },
      { symbol: 'GOOGL', name: 'Alphabet' },
      { symbol: 'META',  name: 'Meta' },
      { symbol: 'TSLA',  name: 'Tesla' },
    ],
  },
  {
    id: 'dow30',
    label: 'Dow Jones 30',
    description: 'DJIA blue-chip components',
    color: '#69F0AE',
    tickers: [
      { symbol: 'AAPL',  name: 'Apple' },
      { symbol: 'AMGN',  name: 'Amgen' },
      { symbol: 'AXP',   name: 'American Express' },
      { symbol: 'BA',    name: 'Boeing' },
      { symbol: 'CAT',   name: 'Caterpillar' },
      { symbol: 'CRM',   name: 'Salesforce' },
      { symbol: 'CSCO',  name: 'Cisco' },
      { symbol: 'CVX',   name: 'Chevron' },
      { symbol: 'DIS',   name: 'Disney' },
      { symbol: 'GS',    name: 'Goldman Sachs' },
      { symbol: 'HD',    name: 'Home Depot' },
      { symbol: 'HON',   name: 'Honeywell' },
      { symbol: 'IBM',   name: 'IBM' },
      { symbol: 'JNJ',   name: 'Johnson & Johnson' },
      { symbol: 'JPM',   name: 'JPMorgan Chase' },
      { symbol: 'KO',    name: 'Coca-Cola' },
      { symbol: 'MCD',   name: "McDonald's" },
      { symbol: 'MMM',   name: '3M' },
      { symbol: 'MRK',   name: 'Merck' },
      { symbol: 'MSFT',  name: 'Microsoft' },
      { symbol: 'NKE',   name: 'Nike' },
      { symbol: 'PG',    name: 'Procter & Gamble' },
      { symbol: 'TRV',   name: 'Travelers' },
      { symbol: 'UNH',   name: 'UnitedHealth' },
      { symbol: 'V',     name: 'Visa' },
      { symbol: 'VZ',    name: 'Verizon' },
      { symbol: 'WMT',   name: 'Walmart' },
      { symbol: 'AMZN',  name: 'Amazon' },
      { symbol: 'NVDA',  name: 'NVIDIA' },
      { symbol: 'SHW',   name: 'Sherwin-Williams' },
    ],
  },
  {
    id: 'nasdaq100',
    label: 'NASDAQ 100',
    description: 'Top 100 non-financial NASDAQ stocks',
    color: '#FFD740',
    tickers: [
      { symbol: 'AAPL',  name: 'Apple' },
      { symbol: 'MSFT',  name: 'Microsoft' },
      { symbol: 'NVDA',  name: 'NVIDIA' },
      { symbol: 'AMZN',  name: 'Amazon' },
      { symbol: 'META',  name: 'Meta' },
      { symbol: 'GOOGL', name: 'Alphabet A' },
      { symbol: 'GOOG',  name: 'Alphabet C' },
      { symbol: 'TSLA',  name: 'Tesla' },
      { symbol: 'AVGO',  name: 'Broadcom' },
      { symbol: 'COST',  name: 'Costco' },
      { symbol: 'NFLX',  name: 'Netflix' },
      { symbol: 'AMD',   name: 'AMD' },
      { symbol: 'QCOM',  name: 'Qualcomm' },
      { symbol: 'TMUS',  name: 'T-Mobile' },
      { symbol: 'INTU',  name: 'Intuit' },
      { symbol: 'AMAT',  name: 'Applied Materials' },
      { symbol: 'ISRG',  name: 'Intuitive Surgical' },
      { symbol: 'TXN',   name: 'Texas Instruments' },
      { symbol: 'AMGN',  name: 'Amgen' },
      { symbol: 'LRCX',  name: 'Lam Research' },
      { symbol: 'MU',    name: 'Micron' },
      { symbol: 'BKNG',  name: 'Booking Holdings' },
      { symbol: 'KLAC',  name: 'KLA Corp' },
      { symbol: 'REGN',  name: 'Regeneron' },
      { symbol: 'ADI',   name: 'Analog Devices' },
      { symbol: 'SNPS',  name: 'Synopsys' },
      { symbol: 'CDNS',  name: 'Cadence Design' },
      { symbol: 'VRTX',  name: 'Vertex Pharma' },
      { symbol: 'PANW',  name: 'Palo Alto Networks' },
      { symbol: 'CRWD',  name: 'CrowdStrike' },
      { symbol: 'MELI',  name: 'MercadoLibre' },
      { symbol: 'ADSK',  name: 'Autodesk' },
      { symbol: 'FTNT',  name: 'Fortinet' },
      { symbol: 'MDLZ',  name: 'Mondelez' },
      { symbol: 'MRVL',  name: 'Marvell Tech' },
      { symbol: 'ORLY',  name: "O'Reilly Auto" },
      { symbol: 'CSX',   name: 'CSX Corp' },
      { symbol: 'ROST',  name: 'Ross Stores' },
      { symbol: 'PAYX',  name: 'Paychex' },
      { symbol: 'DXCM',  name: 'Dexcom' },
      { symbol: 'CPRT',  name: 'Copart' },
      { symbol: 'NXPI',  name: 'NXP Semiconductors' },
      { symbol: 'MNST',  name: 'Monster Beverage' },
      { symbol: 'PCAR',  name: 'PACCAR' },
      { symbol: 'IDXX',  name: 'IDEXX Labs' },
      { symbol: 'CSGP',  name: 'CoStar Group' },
      { symbol: 'ODFL',  name: 'Old Dominion Freight' },
      { symbol: 'VRSK',  name: 'Verisk Analytics' },
      { symbol: 'BIIB',  name: 'Biogen' },
      { symbol: 'AEP',   name: 'American Electric Power' },
      { symbol: 'EXC',   name: 'Exelon' },
      { symbol: 'XEL',   name: 'Xcel Energy' },
      { symbol: 'ANSS',  name: 'ANSYS' },
      { symbol: 'EA',    name: 'Electronic Arts' },
      { symbol: 'DLTR',  name: 'Dollar Tree' },
      { symbol: 'KDP',   name: 'Keurig Dr Pepper' },
      { symbol: 'SBUX',  name: 'Starbucks' },
      { symbol: 'MAR',   name: 'Marriott' },
      { symbol: 'ABNB',  name: 'Airbnb' },
      { symbol: 'CTSH',  name: 'Cognizant' },
      { symbol: 'FAST',  name: 'Fastenal' },
      { symbol: 'WDAY',  name: 'Workday' },
      { symbol: 'TEAM',  name: 'Atlassian' },
      { symbol: 'ILMN',  name: 'Illumina' },
      { symbol: 'EBAY',  name: 'eBay' },
      { symbol: 'ZM',    name: 'Zoom' },
      { symbol: 'TTWO',  name: 'Take-Two Interactive' },
      { symbol: 'GILD',  name: 'Gilead Sciences' },
      { symbol: 'WBA',   name: 'Walgreens Boots' },
      { symbol: 'CEG',   name: 'Constellation Energy' },
      { symbol: 'FSLR',  name: 'First Solar' },
      { symbol: 'ON',    name: 'ON Semiconductor' },
      { symbol: 'GFS',   name: 'GlobalFoundries' },
      { symbol: 'SMCI',  name: 'Super Micro Computer' },
      { symbol: 'ARM',   name: 'Arm Holdings' },
      { symbol: 'TTD',   name: 'The Trade Desk' },
      { symbol: 'DDOG',  name: 'Datadog' },
      { symbol: 'SNOW',  name: 'Snowflake' },
      { symbol: 'ZS',    name: 'Zscaler' },
      { symbol: 'NET',   name: 'Cloudflare' },
      { symbol: 'COIN',  name: 'Coinbase' },
    ],
  },
  {
    id: 'sp500_top50',
    label: 'S&P 500 Top 50',
    description: 'Largest 50 S&P 500 constituents by market cap',
    color: '#FF6D00',
    tickers: [
      { symbol: 'AAPL',  name: 'Apple' },
      { symbol: 'MSFT',  name: 'Microsoft' },
      { symbol: 'NVDA',  name: 'NVIDIA' },
      { symbol: 'AMZN',  name: 'Amazon' },
      { symbol: 'GOOGL', name: 'Alphabet' },
      { symbol: 'META',  name: 'Meta' },
      { symbol: 'TSLA',  name: 'Tesla' },
      { symbol: 'BRK-B', name: 'Berkshire Hathaway B' },
      { symbol: 'AVGO',  name: 'Broadcom' },
      { symbol: 'JPM',   name: 'JPMorgan Chase' },
      { symbol: 'LLY',   name: 'Eli Lilly' },
      { symbol: 'V',     name: 'Visa' },
      { symbol: 'UNH',   name: 'UnitedHealth' },
      { symbol: 'XOM',   name: 'Exxon Mobil' },
      { symbol: 'MA',    name: 'Mastercard' },
      { symbol: 'COST',  name: 'Costco' },
      { symbol: 'HD',    name: 'Home Depot' },
      { symbol: 'NFLX',  name: 'Netflix' },
      { symbol: 'PG',    name: 'Procter & Gamble' },
      { symbol: 'JNJ',   name: 'Johnson & Johnson' },
      { symbol: 'WMT',   name: 'Walmart' },
      { symbol: 'BAC',   name: 'Bank of America' },
      { symbol: 'ABBV',  name: 'AbbVie' },
      { symbol: 'CRM',   name: 'Salesforce' },
      { symbol: 'CVX',   name: 'Chevron' },
      { symbol: 'ORCL',  name: 'Oracle' },
      { symbol: 'MRK',   name: 'Merck' },
      { symbol: 'KO',    name: 'Coca-Cola' },
      { symbol: 'AMD',   name: 'AMD' },
      { symbol: 'PEP',   name: 'PepsiCo' },
      { symbol: 'ACN',   name: 'Accenture' },
      { symbol: 'TMO',   name: 'Thermo Fisher' },
      { symbol: 'MCD',   name: "McDonald's" },
      { symbol: 'ADBE',  name: 'Adobe' },
      { symbol: 'CSCO',  name: 'Cisco' },
      { symbol: 'WFC',   name: 'Wells Fargo' },
      { symbol: 'IBM',   name: 'IBM' },
      { symbol: 'GE',    name: 'GE Aerospace' },
      { symbol: 'AXP',   name: 'American Express' },
      { symbol: 'INTU',  name: 'Intuit' },
      { symbol: 'CAT',   name: 'Caterpillar' },
      { symbol: 'MS',    name: 'Morgan Stanley' },
      { symbol: 'GS',    name: 'Goldman Sachs' },
      { symbol: 'BLK',   name: 'BlackRock' },
      { symbol: 'AMGN',  name: 'Amgen' },
      { symbol: 'RTX',   name: 'RTX Corp' },
      { symbol: 'SPGI',  name: 'S&P Global' },
      { symbol: 'NOW',   name: 'ServiceNow' },
      { symbol: 'T',     name: 'AT&T' },
      { symbol: 'UBER',  name: 'Uber' },
    ],
  },
  {
    id: 'russell_smallcap',
    label: 'Russell Small Caps',
    description: 'High-beta Russell 2000 movers',
    color: '#CF6679',
    tickers: [
      { symbol: 'SMCI',  name: 'Super Micro Computer' },
      { symbol: 'SAIA',  name: 'Saia Inc' },
      { symbol: 'NVST',  name: 'Envista Holdings' },
      { symbol: 'CVNA',  name: 'Carvana' },
      { symbol: 'WING',  name: 'Wingstop' },
      { symbol: 'CELH',  name: 'Celsius Holdings' },
      { symbol: 'FTLF',  name: 'FitLife Brands' },
      { symbol: 'BOOT',  name: 'Boot Barn' },
      { symbol: 'TGTX',  name: 'TG Therapeutics' },
      { symbol: 'ASTS',  name: 'AST SpaceMobile' },
      { symbol: 'JOBY',  name: 'Joby Aviation' },
      { symbol: 'RKT',   name: 'Rocket Companies' },
      { symbol: 'IONQ',  name: 'IonQ' },
      { symbol: 'LUNR',  name: 'Intuitive Machines' },
      { symbol: 'RKLB',  name: 'Rocket Lab' },
      { symbol: 'ACHR',  name: 'Archer Aviation' },
      { symbol: 'TXRH',  name: 'Texas Roadhouse' },
      { symbol: 'MEDP',  name: 'Medpace Holdings' },
      { symbol: 'CRVL',  name: 'CorVel Corp' },
      { symbol: 'LBPH',  name: 'Longboard Pharma' },
      { symbol: 'HIMS',  name: 'Hims & Hers Health' },
      { symbol: 'PRCT',  name: 'PROCEPT BioRobotics' },
      { symbol: 'SBSW',  name: 'Sibanye Stillwater' },
      { symbol: 'RXT',   name: 'Rackspace Technology' },
      { symbol: 'KROS',  name: 'Keros Therapeutics' },
    ],
  },
  {
    id: 'semiconductors',
    label: 'Semiconductors',
    description: 'SOX index key components',
    color: '#7CB9F4',
    tickers: [
      { symbol: 'NVDA',  name: 'NVIDIA' },
      { symbol: 'AMD',   name: 'AMD' },
      { symbol: 'AVGO',  name: 'Broadcom' },
      { symbol: 'QCOM',  name: 'Qualcomm' },
      { symbol: 'TXN',   name: 'Texas Instruments' },
      { symbol: 'AMAT',  name: 'Applied Materials' },
      { symbol: 'LRCX',  name: 'Lam Research' },
      { symbol: 'KLAC',  name: 'KLA Corp' },
      { symbol: 'MU',    name: 'Micron' },
      { symbol: 'INTC',  name: 'Intel' },
      { symbol: 'ADI',   name: 'Analog Devices' },
      { symbol: 'NXPI',  name: 'NXP Semiconductors' },
      { symbol: 'MRVL',  name: 'Marvell Tech' },
      { symbol: 'ON',    name: 'ON Semiconductor' },
      { symbol: 'MPWR',  name: 'Monolithic Power' },
      { symbol: 'WOLF',  name: 'Wolfspeed' },
      { symbol: 'SWKS',  name: 'Skyworks Solutions' },
      { symbol: 'QRVO',  name: 'Qorvo' },
      { symbol: 'SMCI',  name: 'Super Micro Computer' },
      { symbol: 'ARM',   name: 'Arm Holdings' },
      { symbol: 'SOXL',  name: 'Semiconductor Bull 3×' },
      { symbol: 'SOXS',  name: 'Semiconductor Bear 3×' },
    ],
  },
  {
    id: 'etfs',
    label: 'Key ETFs',
    description: 'Index & sector ETFs',
    color: '#B39DDB',
    tickers: [
      { symbol: 'SPY',   name: 'S&P 500' },
      { symbol: 'QQQ',   name: 'NASDAQ 100' },
      { symbol: 'IWM',   name: 'Russell 2000' },
      { symbol: 'DIA',   name: 'Dow Jones 30' },
      { symbol: 'VTI',   name: 'Total US Market' },
      { symbol: 'XLK',   name: 'Technology' },
      { symbol: 'XLF',   name: 'Financials' },
      { symbol: 'XLE',   name: 'Energy' },
      { symbol: 'XLV',   name: 'Health Care' },
      { symbol: 'XLI',   name: 'Industrials' },
      { symbol: 'XLC',   name: 'Communication Services' },
      { symbol: 'XLY',   name: 'Consumer Discretionary' },
      { symbol: 'XLP',   name: 'Consumer Staples' },
      { symbol: 'XLB',   name: 'Materials' },
      { symbol: 'XLRE',  name: 'Real Estate' },
      { symbol: 'XLU',   name: 'Utilities' },
      { symbol: 'GLD',   name: 'Gold' },
      { symbol: 'SLV',   name: 'Silver' },
      { symbol: 'TLT',   name: '20+ Year Treasury' },
      { symbol: 'HYG',   name: 'High Yield Corp Bonds' },
      { symbol: 'ARKK',  name: 'ARK Innovation' },
      { symbol: 'TQQQ',  name: 'NASDAQ 3× Bull' },
      { symbol: 'SQQQ',  name: 'NASDAQ 3× Bear' },
      { symbol: 'UPRO',  name: 'S&P 500 3× Bull' },
    ],
  },
  {
    id: 'ai_cloud',
    label: 'AI & Cloud',
    description: 'AI infrastructure and cloud platforms',
    color: '#00E676',
    tickers: [
      { symbol: 'NVDA',  name: 'NVIDIA' },
      { symbol: 'MSFT',  name: 'Microsoft (Azure)' },
      { symbol: 'GOOGL', name: 'Google (GCP + Gemini)' },
      { symbol: 'AMZN',  name: 'Amazon (AWS)' },
      { symbol: 'META',  name: 'Meta AI' },
      { symbol: 'ORCL',  name: 'Oracle Cloud' },
      { symbol: 'CRM',   name: 'Salesforce AI' },
      { symbol: 'NOW',   name: 'ServiceNow AI' },
      { symbol: 'SNOW',  name: 'Snowflake' },
      { symbol: 'DDOG',  name: 'Datadog' },
      { symbol: 'NET',   name: 'Cloudflare' },
      { symbol: 'ZS',    name: 'Zscaler' },
      { symbol: 'CRWD',  name: 'CrowdStrike' },
      { symbol: 'PANW',  name: 'Palo Alto Networks' },
      { symbol: 'PLTR',  name: 'Palantir' },
      { symbol: 'AI',    name: 'C3.ai' },
      { symbol: 'PATH',  name: 'UiPath' },
      { symbol: 'GTLB',  name: 'GitLab' },
      { symbol: 'MDB',   name: 'MongoDB' },
      { symbol: 'ESTC',  name: 'Elastic' },
      { symbol: 'SMCI',  name: 'Super Micro' },
      { symbol: 'ARM',   name: 'Arm Holdings' },
    ],
  },
  {
    id: 'crypto',
    label: 'Crypto & Blockchain',
    description: 'Digital assets and crypto-adjacent equities',
    color: '#FFD740',
    tickers: [
      { symbol: 'BTC-USD',  name: 'Bitcoin' },
      { symbol: 'ETH-USD',  name: 'Ethereum' },
      { symbol: 'SOL-USD',  name: 'Solana' },
      { symbol: 'BNB-USD',  name: 'BNB' },
      { symbol: 'XRP-USD',  name: 'XRP' },
      { symbol: 'DOGE-USD', name: 'Dogecoin' },
      { symbol: 'ADA-USD',  name: 'Cardano' },
      { symbol: 'AVAX-USD', name: 'Avalanche' },
      { symbol: 'COIN',     name: 'Coinbase' },
      { symbol: 'MSTR',     name: 'MicroStrategy' },
      { symbol: 'RIOT',     name: 'Riot Platforms' },
      { symbol: 'MARA',     name: 'Marathon Digital' },
      { symbol: 'HUT',      name: 'Hut 8 Mining' },
      { symbol: 'CLSK',     name: 'CleanSpark' },
      { symbol: 'IBIT',     name: 'iShares Bitcoin ETF' },
      { symbol: 'FBTC',     name: 'Fidelity Bitcoin ETF' },
    ],
  },
]
